# Generated by Django 5.2.8 on 2025-11-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryuser',
            name='allowed_locations',
            field=models.CharField(blank=True, help_text='Lista locațiilor pe care utilizatorul are voie să editeze (separate prin virgulă, ex: IAS,FRA,QRO).', max_length=255),
        ),
        migrations.AddField(
            model_name='inventoryuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('viewer', 'Viewer')], default='viewer', help_text='Rolul în aplicația de inventar (admin / staff / viewer).', max_length=16),
        ),
    ]
